"""Run promptlint against examples/example_prompts.json and write a validation report.

This is the script behind the README's "Validation" section: it scores every
example prompt (deliberately spanning weak / medium / strong) and writes the
results to examples/validation_report.md so the scores in the README are
reproducible, not hand-typed.

Usage:
    export ANTHROPIC_API_KEY=sk-ant-...
    python examples/run_validation.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from promptlint.scorer import score_prompt  # noqa: E402

HERE = Path(__file__).resolve().parent
EXAMPLES_FILE = HERE / "example_prompts.json"
REPORT_FILE = HERE / "validation_report.md"


def main() -> None:
    examples = json.loads(EXAMPLES_FILE.read_text(encoding="utf-8"))

    lines = ["# promptlint validation report", "", "Generated by `examples/run_validation.py`.", ""]
    lines.append("| Example | Overall | Notes |")
    lines.append("|---|---|---|")

    details = []

    for ex in examples:
        print(f"Scoring: {ex['id']} ({ex['label']})...", file=sys.stderr)
        result = score_prompt(ex["prompt"])
        lines.append(f"| {ex['label']} | {result.overall}/5 | see detail below |")
        details.append((ex, result))

    lines.append("")
    lines.append("## Detail")
    lines.append("")

    for ex, result in details:
        lines.append(f"### {ex['label']}")
        lines.append("")
        lines.append(f"> {ex['prompt']}")
        lines.append("")
        lines.append(f"**Overall: {result.overall}/5**")
        lines.append("")
        for key, score in result.scores.items():
            lines.append(f"- **{key}**: {score}/5 — {result.feedback.get(key, '')}")
        if result.clarifying_questions:
            lines.append("")
            lines.append("Questions worth answering:")
            for q in result.clarifying_questions:
                lines.append(f"- {q}")
        lines.append("")

    REPORT_FILE.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {REPORT_FILE}", file=sys.stderr)


if __name__ == "__main__":
    main()
